dist: trusty
language: node_js

node_js:
  - '4.4.2'

script:
  - git config --global user.email "build@travis-ci.org"
  - git config --global user.name "Travis gh pages"
  - cd modules/der-reader
  - npm install
  - npm run build
  - cd dist
  - ls
  - git status
  - git init
  - git add .
  - git commit -m "Deploy to Github Pages"
  - git status
  - git push --force --quiet "https://${GITHUB_API_TOKEN}@github.com/makinacorpus/accessimap-lecteur-der.git" master:gh-pages > /dev/null 2>&1

cache:
  directories:
    - node_modules

deploy:
  provider: releases
  api_key: "$GITHUB_API_TOKEN"
  file_glob: true
  file:
    - "$TRAVIS_BUILD_DIR/electron/dist/accessimap*"
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
